/**
 * Premium Sales Tools Database (Curated & Real-World Data)
 * 80+ real-world B2B sales tools across 8 main categories with verified details.
 */
export const salesTools = [
  // --- Prospecting & enrichment ---
  {
    id: "clay",
    name: "Clay",
    description: "Build enriched prospect lists using 50+ B2B data sources and write highly personalized cold outreach using custom AI agents.",
    is_ai: true,
    category: "Prospecting",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "LinkedIn",
    url: "https://clay.com",
    tags: ["Data Enrichment", "GPT-4", "Automation"]
  },
  {
    id: "seamless-ai",
    name: "Seamless.AI",
    description: "B2B search engine for finding direct dials, cell phone numbers, and verified business email addresses in real time.",
    is_ai: true,
    category: "Prospecting",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "Salesforce",
    url: "https://seamless.ai",
    tags: ["Direct Dials", "Real-Time Search", "Email Finder"]
  },
  {
    id: "clearbit",
    name: "Clearbit",
    description: "Enrich records with firmographic and tech stack data to optimize conversion paths and identify high-intent accounts.",
    is_ai: true,
    category: "Prospecting",
    target_market: "Mid-Market",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://clearbit.com",
    tags: ["Technographics", "Lead Reveal", "Data Enrichment"]
  },
  {
    id: "linkedin-sales-nav",
    name: "LinkedIn Sales Navigator",
    description: "The gold standard for finding buyer personas, tracking job changes, and sending InMail outreach to target prospects.",
    is_ai: true,
    category: "Prospecting",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://linkedin.com",
    tags: ["InMail", "Lead Lists", "B2B Database"]
  },
  {
    id: "vainu",
    name: "Vainu",
    description: "Nordic company database offering technographic profiles and real-time triggers to qualify accounts and sync updates.",
    is_ai: true,
    category: "Prospecting",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://vainu.com",
    tags: ["Company Data", "EU Compliance", "Triggers"]
  },
  {
    id: "dealfront",
    name: "Dealfront",
    description: "B2B platform combining company databases with IP address intelligence to reveal site visitors and extract direct contact lists.",
    is_ai: false,
    category: "Prospecting",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://dealfront.com",
    tags: ["EU GDPR Data", "Website Visitor IP", "B2B Leads"]
  },
  {
    id: "datanyze",
    name: "Datanyze",
    description: "Find contact phone numbers and emails directly from social profiles while inspecting technographic scripts.",
    is_ai: false,
    category: "Prospecting",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://datanyze.com",
    tags: ["Chrome Extension", "Cold Calling", "Email Finder"]
  },

  // --- Lead Gen ---
  {
    id: "apollo",
    name: "Apollo.io",
    description: "Find buyer emails and direct phone numbers, create outbound sequence flows, and generate AI-guided templates.",
    is_ai: true,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "Salesforce",
    url: "https://apollo.io",
    tags: ["Sequences", "AI Writing", "Data Finder"]
  },
  {
    id: "lusha",
    name: "Lusha",
    description: "Locate phone numbers and verified business emails instantly for targets on LinkedIn and company web domains.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://lusha.com",
    tags: ["Direct Dials", "B2B Contacts", "Lead Capture"]
  },
  {
    id: "hunter",
    name: "Hunter.io",
    description: "Locate professional email addresses by domain, verify address deliverability, and run simple email outbound sequences.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://hunter.io",
    tags: ["Email Verifier", "Domain Search", "Lead Lists"]
  },
  {
    id: "zoominfo",
    name: "ZoomInfo",
    description: "Database featuring verified corporate direct dials, emails, intent buying signals, and technographic details.",
    is_ai: true,
    category: "Lead Gen",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://zoominfo.com",
    tags: ["Intent Signals", "Corporate Dials", "Enrichment"]
  },
  {
    id: "cognism",
    name: "Cognism",
    description: "GDPR-compliant global B2B phone number and email database specializing in phone-verified mobile numbers.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://cognism.com",
    tags: ["GDPR Compliance", "Mobile Dials", "Direct Lines"]
  },
  {
    id: "leadfeeder",
    name: "Leadfeeder",
    description: "Identify companies visiting your website, tracking their pages viewed and routing high-intent deals to your CRM.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://leadfeeder.com",
    tags: ["Visitor IP", "Lead Scoring", "Website Tracking"]
  },
  {
    id: "uplead",
    name: "Uplead",
    description: "B2B database offering verified emails with a 95% accuracy guarantee, enabling search filter lists to export.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://uplead.com",
    tags: ["Data Accuracy", "Email Finder", "Data Enrichment"]
  },
  {
    id: "kaspr",
    name: "Kaspr",
    description: "Extract phone numbers and email addresses in one click while browsing social networks and B2B profiles.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://kaspr.io",
    tags: ["LinkedIn Extension", "Direct Dials", "Emails Finder"]
  },
  {
    id: "rocketreach",
    name: "RocketReach",
    description: "Search platform containing emails and phone numbers for over 450 million professionals worldwide.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "LinkedIn",
    url: "https://rocketreach.co",
    tags: ["Email Lookup", "B2B Database", "Phone Numbers"]
  },
  {
    id: "findymail",
    name: "Findymail",
    description: "Scrape B2B websites and extensions, generating clean list files with verified, non-catch-all email details.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://findymail.com",
    tags: ["Verified Emails", "Scraper Tool", "List Cleaning"]
  },
  {
    id: "wiza",
    name: "Wiza",
    description: "Convert LinkedIn queries and searches into list files of verified B2B emails and mobile phone numbers.",
    is_ai: true,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://wiza.co",
    tags: ["LinkedIn Scraper", "Emails Finder", "Phone Numbers"]
  },
  {
    id: "salesintel",
    name: "SalesIntel",
    description: "B2B contact finder focusing on human-verified details for IT, technology, and corporate leadership roles.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://salesintel.blogspot.com",
    tags: ["B2B Data", "Direct Dials", "Technographics"]
  },
  {
    id: "skrapp-io",
    name: "Skrapp.io",
    description: "Extract professional email address structures from LinkedIn profiles and construct domain databases.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://skrapp.io",
    tags: ["LinkedIn Emails", "Domain Search", "Lead Lists"]
  },
  {
    id: "aeroleads",
    name: "AeroLeads",
    description: "Prospecting assistant that extracts email and cell numbers from multiple platforms and uploads directly to your CRM.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Chrome Extension",
    integration: "LinkedIn",
    url: "https://aeroleads.com",
    tags: ["Email Finder", "Phone Numbers", "Prospect Lists"]
  },
  {
    id: "voila-norbert",
    name: "Voila Norbert",
    description: "Locate and verify email addresses for corporate contacts, matching names and domains to build outbound databases.",
    is_ai: false,
    category: "Lead Gen",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Gmail",
    url: "https://voilanorbert.com",
    tags: ["Email Finder", "Lead Generation", "Email Verifier"]
  },

  // --- CRM ---
  {
    id: "hubspot-crm",
    name: "HubSpot CRM",
    description: "Inbound CRM that manages marketing pipelines, lead interactions, and customer support tickets in a unified portal.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Gmail",
    url: "https://hubspot.com",
    tags: ["Pipeline", "Contacts", "Traditional CRM"]
  },
  {
    id: "salesforce-crm",
    name: "Salesforce CRM",
    description: "The global leader in cloud CRM software, allowing custom workflows, dashboards, and enterprise account management.",
    is_ai: true,
    category: "CRM",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Desktop App",
    integration: "Salesforce",
    url: "https://salesforce.com",
    tags: ["Sales Cloud", "Custom Workflows", "Enterprise"]
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "Pipeline-focused CRM built to guide sales activities and track visual transaction boards for small to mid-size teams.",
    is_ai: true,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://pipedrive.com",
    tags: ["Pipeline", "Activity-Based", "Deals Board"]
  },
  {
    id: "close-crm",
    name: "Close CRM",
    description: "Outbound-focused CRM containing integrated VoIP phone dialing, SMS, and email sequence templates inside the portal.",
    is_ai: true,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Desktop App",
    integration: "Gmail",
    url: "https://close.com",
    tags: ["Built-in Calling", "Built-in SMS", "Email Sequences"]
  },
  {
    id: "streak-crm",
    name: "Streak CRM",
    description: "CRM built directly into Google Workspace, allowing pipeline management, mail merges, and sharing inside Gmail.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "Gmail",
    url: "https://streak.com",
    tags: ["Gmail CRM", "Mail Merge", "Pipeline"]
  },
  {
    id: "zoho-crm",
    name: "Zoho CRM",
    description: "Configurable global CRM with Zia AI assistant, sales forecasts, and integrations into the Zoho ecosystem.",
    is_ai: true,
    category: "CRM",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://zoho.com/crm",
    tags: ["Zia Assistant", "Customizable", "Multi-channel"]
  },
  {
    id: "freshsales",
    name: "Freshsales",
    description: "Sales CRM featuring AI-based contact scoring, built-in cloud telephony, and visual pipeline metrics.",
    is_ai: true,
    category: "CRM",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Gmail",
    url: "https://freshworks.com/freshsales",
    tags: ["Contact Scoring", "Telephony", "Freshworks Sync"]
  },
  {
    id: "zendesk-sell",
    name: "Zendesk Sell",
    description: "Sales pipeline CRM combining support ticketing records with client management data for account support teams.",
    is_ai: false,
    category: "CRM",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Mobile App",
    integration: "Salesforce",
    url: "https://zendesk.com/sell",
    tags: ["Zendesk Support", "Pipeline", "Contact Database"]
  },
  {
    id: "copper-crm",
    name: "Copper CRM",
    description: "CRM built specifically for Google Workspace users, auto-syncing contacts from emails and calendar events.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Gmail",
    url: "https://copper.com",
    tags: ["Google CRM", "Auto-Sync", "Contact Lists"]
  },
  {
    id: "nimble-crm",
    name: "Nimble CRM",
    description: "Social-focused CRM that compiles social profiles, emails, and phone logs into a unified dashboard.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://nimble.com",
    tags: ["Social Insights", "Contact Manager", "Shared Inbox"]
  },
  {
    id: "insightly-crm",
    name: "Insightly CRM",
    description: "CRM combining standard pipeline tracking with post-sale project management templates and workflows.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://insightly.com",
    tags: ["Post-Sale Projects", "CRM", "Custom Integrations"]
  },
  {
    id: "capsule-crm",
    name: "Capsule CRM",
    description: "Simple customer relationship manager focused on contact logs, pipeline dashboards, and basic tasks.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Gmail",
    url: "https://capsulecrm.com",
    tags: ["Contact Log", "Deals", "Tasks"]
  },
  {
    id: "keap",
    name: "Keap",
    description: "Combined CRM and marketing automation suite built for small businesses to track sales, invoices, and campaigns.",
    is_ai: false,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://keap.com",
    tags: ["Infusionsoft", "Automation", "Invoicing"]
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    description: "Combined customer experience automation tool featuring marketing campaigns, automated emails, and sales pipeline CRM.",
    is_ai: true,
    category: "CRM",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://activecampaign.com",
    tags: ["Marketing Automation", "Campaigns", "Contact Deals"]
  },

  // --- Outreach & Sales Engagement ---
  {
    id: "lavender",
    name: "Lavender",
    description: "Real-time AI email assistant analyzing your messages, grading readability, and writing personalized sales emails.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Chrome Extension",
    integration: "Gmail",
    url: "https://lavender.ai",
    tags: ["Email Coach", "Writing Assistant", "Outbound"]
  },
  {
    id: "outreach-io",
    name: "Outreach.io",
    description: "Enterprise sales execution platform optimizing outbound sequences, call logs, and forecasting analytics.",
    is_ai: true,
    category: "Outreach",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Gmail",
    url: "https://outreach.io",
    tags: ["Sequences", "Sales Execution", "Outbound Analytics"]
  },
  {
    id: "lemlist",
    name: "Lemlist",
    description: "Cold email outreach platform allowing image and video customization, cold sequences, and automatic domain warmup.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "LinkedIn",
    url: "https://lemlist.com",
    tags: ["Cold Email", "Custom Images", "Deliverability"]
  },
  {
    id: "woodpecker",
    name: "Woodpecker",
    description: "Cold email sequence software designed to optimize inbox deliverability and follow-up paths for prospecting lists.",
    is_ai: false,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Outlook",
    url: "https://woodpecker.co",
    tags: ["Deliverability", "Sequences", "Outlook Outbound"]
  },
  {
    id: "mailshake",
    name: "Mailshake",
    description: "Outbound campaign coordinator featuring cold email merge templates, task scheduling, and integrated dialing.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Gmail",
    url: "https://mailshake.com",
    tags: ["Cold Campaigns", "Sales Dialer", "Mail Merge"]
  },
  {
    id: "reply-io",
    name: "Reply.io",
    description: "Multi-channel sales engagement platform using an AI assistant to compose drafts and verify phone dials.",
    is_ai: true,
    category: "Outreach",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "LinkedIn",
    url: "https://reply.io",
    tags: ["Multichannel Sequences", "AI Assistant", "B2B Data"]
  },
  {
    id: "yesware",
    name: "Yesware",
    description: "Email tracking extension for Outlook and Gmail, saving sequence templates and tracking link click metrics.",
    is_ai: false,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "Gmail",
    url: "https://yesware.com",
    tags: ["Email Tracking", "Templates", "Salesforce Link"]
  },
  {
    id: "mixmax",
    name: "Mixmax",
    description: "Gmail productivity extension allowing scheduled emails, link clicks tracking, surveys, and calendar invites.",
    is_ai: false,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "Gmail",
    url: "https://mixmax.com",
    tags: ["Email Tracking", "Scheduling Link", "Polls"]
  },
  {
    id: "klenty",
    name: "Klenty",
    description: "Sales engagement platform automating cold outreach sequences across email, LinkedIn, calls, and SMS.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://klenty.com",
    tags: ["Sequences", "LinkedIn Automation", "Outbound Flow"]
  },
  {
    id: "outplay",
    name: "Outplay",
    description: "Sales execution tool coordinating outbound calling scripts, email tracks, and social messaging sequences.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://outplayhq.com",
    tags: ["Sales Engagement", "Call Logs", "Multichannel"]
  },
  {
    id: "salesloft",
    name: "Salesloft",
    description: "Enterprise sales engagement software streamlining pipelines, call records, and follow-up task sequences.",
    is_ai: true,
    category: "Outreach",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://salesloft.com",
    tags: ["Enterprise Sequences", "Sales Engagement", "Call Logs"]
  },
  {
    id: "overloop",
    name: "Overloop",
    description: "Multi-channel outreach tool managing cold email sends, LinkedIn tasks, and dialing logs.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "LinkedIn",
    url: "https://overloop.com",
    tags: ["LinkedIn Scraper", "Cold Sequences", "Dialer Integration"]
  },
  {
    id: "quickmail",
    name: "QuickMail.io",
    description: "Deliverability-focused cold email client that coordinates shared inboxes and schedules follow-up tasks.",
    is_ai: false,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Outlook",
    url: "https://quickmail.io",
    tags: ["Email Deliverability", "Cold Emails", "Inboxes"]
  },
  {
    id: "smartreach-io",
    name: "SmartReach.io",
    description: "Multi-channel outreach utility focusing on cold email sequences, deliverability warmup, and LinkedIn sync.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Outlook",
    url: "https://smartreach.io",
    tags: ["Cold Outbound", "Shared Inbox", "Warmup Tools"]
  },
  {
    id: "gmass",
    name: "GMass",
    description: "Mail merge tool integrated into Gmail, facilitating cold campaigns and follow-up templates.",
    is_ai: false,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "Gmail",
    url: "https://gmass.co",
    tags: ["Gmail Merge", "Cold Mail", "Autofollow"]
  },
  {
    id: "autoklose",
    name: "Autoklose",
    description: "Email engagement platform featuring built-in lead directories and cold sequence template logs.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://autoklose.com",
    tags: ["Cold Emailing", "Contact Database", "Email Analytics"]
  },
  {
    id: "saleshandy",
    name: "Saleshandy",
    description: "Automate cold email campaigns, implement deliverability warmups, and manage shared user responses.",
    is_ai: true,
    category: "Outreach",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Gmail",
    url: "https://saleshandy.com",
    tags: ["Campaign Sequences", "Warmup Tools", "Deliverability"]
  },

  // --- Conversation Intelligence & Coaching ---
  {
    id: "gong",
    name: "Gong.io",
    description: "Enterprise revenue intelligence analyzing video meetings, call recordings, and emails to compile deal risks.",
    is_ai: true,
    category: "Coaching",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://gong.io",
    tags: ["Conversation Intelligence", "Coaching", "Deal Risks"]
  },
  {
    id: "chorus",
    name: "Chorus by ZoomInfo",
    description: "Conversation intelligence recording sales calls and indexing competitor mentions, questions, and objection handling.",
    is_ai: true,
    category: "Coaching",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://zoominfo.com/products/chorus",
    tags: ["Call Recording", "ZoomInfo Integration", "Transcriptions"]
  },
  {
    id: "jiminny",
    name: "Jiminny",
    description: "Conversation intelligence software analyzing sales transcripts, talk ratios, and OB cues to coach reps.",
    is_ai: true,
    category: "Coaching",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://jiminny.com",
    tags: ["Call Coaching", "Objection Handling", "Transcripts"]
  },
  {
    id: "avoma",
    name: "Avoma",
    description: "AI meeting assistant that records conference calls, generates structured summaries, and updates CRM deal notes.",
    is_ai: true,
    category: "Coaching",
    target_market: "Mid-Market",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://avoma.com",
    tags: ["Meeting Assistant", "AI Summary", "Notes Sync"]
  },
  {
    id: "fathom",
    name: "Fathom",
    description: "Free AI notetaker for Zoom, Google Meet, and Microsoft Teams that generates bullet-point meeting summaries.",
    is_ai: true,
    category: "Coaching",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Desktop App",
    integration: "HubSpot",
    url: "https://fathom.video",
    tags: ["AI Notetaker", "Transcripts", "Meeting Recorder"]
  },
  {
    id: "fireflies-ai",
    name: "Fireflies.ai",
    description: "AI search and transcription assistant joining calendar links to record meeting transcripts and highlights.",
    is_ai: true,
    category: "Coaching",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://fireflies.ai",
    tags: ["AI Assistant", "Transcripts", "Google Meet Integration"]
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    description: "Real-time meeting voice transcription utility compiling search notes and summary action points.",
    is_ai: true,
    category: "Coaching",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Gmail",
    url: "https://otter.ai",
    tags: ["Voice Transcription", "Audio Recording", "AI Notetaker"]
  },
  {
    id: "execvision",
    name: "ExecVision",
    description: "Call analytics tool evaluating representative coaching scripts, objections, and conversation tracking.",
    is_ai: true,
    category: "Coaching",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://execvision.com",
    tags: ["Call Coaching", "Objections Analysis", "Performance"]
  },
  {
    id: "refract-ai",
    name: "Refract",
    description: "Coaching engine scoring sales call transcripts to highlight representative performance improvements.",
    is_ai: true,
    category: "Coaching",
    target_market: "Mid-Market",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://refract.ai",
    tags: ["Call Coaching", "Objections", "Performance Metrics"]
  },
  {
    id: "salesken-ai",
    name: "Salesken",
    description: "Real-time conversational assistant supplying representatives with scripts and cues during live sales calls.",
    is_ai: true,
    category: "Coaching",
    target_market: "Mid-Market",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://salesken.ai",
    tags: ["Real-Time Cues", "Live Coaching", "AI Playbooks"]
  },
  {
    id: "pickle-ai",
    name: "Pickle",
    description: "AI-powered call compiler summarizing video meetings, tracking competitor mentions, and updating CRM notes.",
    is_ai: true,
    category: "Coaching",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://pickleai.com",
    tags: ["Meeting Summary", "Zoom Integration", "Transcripts"]
  },
  {
    id: "clari-copilot",
    name: "Clari Copilot",
    description: "Real-time conversational assistant providing representatives with script tips and CRM lookups during video conferences.",
    is_ai: true,
    category: "Coaching",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://clari.com/copilot",
    tags: ["Conversation Intelligence", "Real-Time Cards", "Recording"]
  },

  // --- Meeting Scheduling ---
  {
    id: "calendly",
    name: "Calendly",
    description: "The classic scheduling automation link coordinator that integrates with personal calendars to book meetings.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://calendly.com",
    tags: ["Calendar Link", "Integrations", "Scheduling"]
  },
  {
    id: "chili-piper",
    name: "Chili Piper",
    description: "Lead routing and instant scheduler widget qualifying website leads before booking round-robin demos.",
    is_ai: false,
    category: "Scheduling",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Chrome Extension",
    integration: "Salesforce",
    url: "https://chilipiper.com",
    tags: ["Lead Routing", "Round Robin", "Instant Booking"]
  },
  {
    id: "oncehub",
    name: "OnceHub",
    description: "Qualified booking coordinator, routing demo requests and scheduling calls across sales and service reps.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://oncehub.com",
    tags: ["Round Robin", "Lead Routing", "Scheduling link"]
  },
  {
    id: "youcanbook-me",
    name: "YouCanBook.me",
    description: "Customizable booking client coordinating customer appointment grids, reminders, and calendar blocks.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://youcanbook.me",
    tags: ["Calendar link", "Booking page", "Reminders"]
  },
  {
    id: "savvycal",
    name: "SavvyCal",
    description: "Interactive calendar link scheduler designed to overlay calendars and reduce scheduling friction.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Gmail",
    url: "https://savvycal.com",
    tags: ["Meeting scheduling", "Calendar overlay", "UX design"]
  },
  {
    id: "acuity-scheduling",
    name: "Acuity Scheduling",
    description: "Appointment client for booking demos, processing downpayments, and managing representative calendars.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Outlook",
    url: "https://acuityscheduling.com",
    tags: ["Appointment booking", "Calendars", "Payments"]
  },
  {
    id: "doodle",
    name: "Doodle",
    description: "Group polling scheduler coordinates calendar availability to select the best group meeting times.",
    is_ai: false,
    category: "Scheduling",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Outlook",
    url: "https://doodle.com",
    tags: ["Group Polls", "Calendar Link", "Scheduling"]
  },

  // --- e-Sign & Document Tracking ---
  {
    id: "docusign",
    name: "DocuSign",
    description: "The global leader in electronic signatures, managing secure legal agreements and workflow records.",
    is_ai: false,
    category: "e-Sign",
    target_market: "Enterprise",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://docusign.com",
    tags: ["e-Signatures", "Legal Signing", "Contracts"]
  },
  {
    id: "pandadoc",
    name: "PandaDoc",
    description: "Proposal tracking tool helping representatives compose document templates, quote lines, and secure electronic signatures.",
    is_ai: true,
    category: "e-Sign",
    target_market: "SMB",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://pandadoc.com",
    tags: ["Proposals", "Quotes", "e-Signatures"]
  },
  {
    id: "adobe-sign",
    name: "Adobe Acrobat Sign",
    description: "Secure e-signature app compliant with global legal document criteria, integrating with Adobe PDFs.",
    is_ai: false,
    category: "e-Sign",
    target_market: "Enterprise",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://adobe.com/sign",
    tags: ["PDF Signatures", "Enterprise Legal", "Agreement logs"]
  },
  {
    id: "dropbox-sign",
    name: "Dropbox Sign (HelloSign)",
    description: "Lightweight electronic signature client offering document template libraries, audit trails, and signing API.",
    is_ai: false,
    category: "e-Sign",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Gmail",
    url: "https://hellosign.com",
    tags: ["Dropbox Sign", "PDF Signing", "Agreement API"]
  },
  {
    id: "signnow",
    name: "SignNow",
    description: "Secure document signer coordinating contract templates, signing roles, and document status updates.",
    is_ai: false,
    category: "e-Sign",
    target_market: "SMB",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Outlook",
    url: "https://signnow.com",
    tags: ["PDF Signer", "Document status", "e-Signatures"]
  },
  {
    id: "getaccept",
    name: "GetAccept",
    description: "Digital sales room platform featuring contract template builds, pitch tracking, and secure electronic signatures.",
    is_ai: true,
    category: "e-Sign",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://getaccept.com",
    tags: ["Digital Sales Room", "Video proposals", "e-Signatures"]
  },
  {
    id: "proposify",
    name: "Proposify",
    description: "Proposal creator software generating design templates, lines, and secure electronic signatures.",
    is_ai: false,
    category: "e-Sign",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://proposify.com",
    tags: ["Proposals", "Contracts", "e-Signatures"]
  },
  {
    id: "docsend",
    name: "DocSend",
    description: "Dropbox document sharing client tracking slide reviews, link downloads, and recipient contact details.",
    is_ai: false,
    category: "e-Sign",
    target_market: "SMB",
    pricing: "Free Trial",
    platform: "Web App",
    integration: "Gmail",
    url: "https://docsend.com",
    tags: ["Document Tracking", "Pitch Deck Analytics", "Sharing link"]
  },
  {
    id: "concord",
    name: "Concord",
    description: "Contract lifecycle manager facilitating online negotiation, approval logs, and electronic signatures.",
    is_ai: false,
    category: "e-Sign",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://concordnow.com",
    tags: ["Contract Negotiation", "Approve log", "e-Signatures"]
  },
  {
    id: "qwilr",
    name: "Qwilr",
    description: "Interactive webpage proposals generator featuring dynamic quote calculators, e-signatures, and viewer statistics.",
    is_ai: true,
    category: "e-Sign",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://qwilr.com",
    tags: ["Web Proposal", "Pricing Calculators", "Analytics"]
  },

  // --- Revenue Operations & Analytics ---
  {
    id: "clari",
    name: "Clari",
    description: "Revenue intelligence coordinating sales pipelines, forecasting calculations, and account deal health.",
    is_ai: true,
    category: "Analytics",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://clari.com",
    tags: ["Forecasting", "Revenue Operations", "Deal Health"]
  },
  {
    id: "people-ai",
    name: "People.ai",
    description: "Activity tracker analyzing emails and calendar bookings, scoring pipelines, and updating CRM records.",
    is_ai: true,
    category: "Analytics",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://people.ai",
    tags: ["Activity Capture", "Revenue Insights", "AI Scoring"]
  },
  {
    id: "boostup-ai",
    name: "BoostUp.ai",
    description: "Predictive analytics database scoring deal health, pipeline risk logs, and representative forecasting drafts.",
    is_ai: true,
    category: "Analytics",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://boostup.ai",
    tags: ["Forecasting", "Deal Scoring", "Pipeline Risk"]
  },
  {
    id: "revenue-io",
    name: "Revenue.io",
    description: "Real-time sales guidance compiler coordinating VoIP dialer calls and pipeline analytics dashboards.",
    is_ai: true,
    category: "Analytics",
    target_market: "Enterprise",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://revenue.io",
    tags: ["Sales Dialer", "Activity Capture", "Real-Time Cue"]
  },
  {
    id: "ebsta",
    name: "Ebsta",
    description: "Relationship analytics module tracking email interactions to rank pipeline risks and forecast metrics.",
    is_ai: true,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://ebsta.com",
    tags: ["Relationship Score", "Salesforce Sync", "Forecasting"]
  },
  {
    id: "insightsquared",
    name: "InsightSquared",
    description: "Revenue operations dashboard compiling sales activity logs and quota attribution metrics.",
    is_ai: false,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://insightsquared.com",
    tags: ["Revenue Operations", "Sales Metrics", "Dashboards"]
  },
  {
    id: "kluster",
    name: "Kluster",
    description: "Sales intelligence forecasting and analytics platform compiling representative dashboard scorecards.",
    is_ai: false,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Subscription",
    platform: "Web App",
    integration: "HubSpot",
    url: "https://kluster.com",
    tags: ["Forecasting", "Revenue Metrics", "Pipeline Analytics"]
  },
  {
    id: "troops-ai",
    name: "Troops.ai",
    description: "Workflow manager routing Salesforce deal alerts and dashboard metrics directly to corporate Slack channels.",
    is_ai: true,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Custom Quote",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://troops.ai",
    tags: ["Slack Alerts", "Salesforce Sync", "Workflow Routing"]
  },
  {
    id: "scratchpad",
    name: "Scratchpad",
    description: "Chrome Workspace designed for rapid note-taking, pipeline edits, and instant Salesforce database updates.",
    is_ai: false,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Free Plan",
    platform: "Chrome Extension",
    integration: "Salesforce",
    url: "https://scratchpad.com",
    tags: ["Sales Notes", "Salesforce Sync", "Pipeline Update"]
  },
  {
    id: "dooly",
    name: "Dooly",
    description: "Sales notepad syncing representative transcripts, deal objections, and notes directly into CRM portals.",
    is_ai: true,
    category: "Analytics",
    target_market: "Mid-Market",
    pricing: "Free Plan",
    platform: "Web App",
    integration: "Salesforce",
    url: "https://dooly.ai",
    tags: ["Sales Notes", "Salesforce Sync", "Playbooks"]
  }
];

// Export B2B filtering dimensions
export const filterCategories = ["All", "Prospecting", "Lead Gen", "CRM", "Outreach", "Coaching", "Scheduling", "e-Sign", "Analytics"];
export const filterMarkets = ["All", "SMB", "Mid-Market", "Enterprise"];
export const filterPricings = ["All", "Free Plan", "Free Trial", "Subscription", "Custom Quote"];
export const filterPlatforms = ["All", "Web App", "Chrome Extension", "Desktop App", "Mobile App"];
export const filterIntegrations = ["All", "Salesforce", "HubSpot", "LinkedIn", "Gmail", "Outlook"];
export const techTypes = [
  { label: "All Tools", value: "All" },
  { label: "AI-Powered", value: "AI" },
  { label: "Traditional", value: "Traditional" }
];
